import Head from 'next/head'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs,code for coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Script strategy='lazyOnload'></Script>

      <main className={styles.main}>
        <h1 className={styles.title}>
       Blog For A New Coder</h1>
        <img src='/pexels-photo-843226.jpeg' width={1325} height={400}/>
        <p className={styles.description}>
         A Blog For Coders By A Coder
        </p>
         
         <div className="blog">
          <div className="blogs">
            <h1>How to learn javascript in 2022</h1>
            <p> javascript is the language used to design logic for the server site</p>
          </div>

          <div className="blogs">
            <h3>How to learn ReactJs in 2022</h3>
            <p> javascript is the language used to design logic for the client site</p>
          </div>

          <div className="blogs">
            <h3>How to learn NodeJs in 2022</h3>
            <p> javascript is the language used to design logic for the server site</p>
          </div>
          
         </div>
        
      </main>

     
    </div>
  )
}
